#!/usr/bin/env php
<?php

/*
 * This file is part of tsparse.
 * https://github.com/martin-helmich/ts-parse
 *
 * (C) 2014 Martin Helmich <kontakt@martin-helmich.de>
 *
 * For license information, view the LICENSE.md file.
 */

use Helmich\TypoScriptParser\TypoScriptParserExtension;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Console\Application;
use Symfony\Component\Config\FileLocator;

if (file_exists(__DIR__ . '/vendor/autoload.php'))
{
    require_once __DIR__ . '/vendor/autoload.php';
}
else if (file_exists(__DIR__ . '/../../autoload.php'))
{
    /** @noinspection PhpIncludeInspection */
    require_once __DIR__ . '/../../autoload.php';
}
else
{
    die('Could not find an autoload.php. Did you set up all dependencies?');
}

$container = new ContainerBuilder();
$container->setParameter('dir.cwd', getcwd());
$container->setParameter('dir.tslint_root', basename(__DIR__));
$container->registerExtension(new TypoScriptParserExtension());

$loader    = new YamlFileLoader($container, new FileLocator(__DIR__));
$loader->load('services.yml');

$container->loadFromExtension('typoscript_parser');
$container->compile();

$application = new Application();

/** @noinspection PhpParamsInspection */
$application->add($container->get('tokenize_command'));
$application->add($container->get('lint_command'));
$application->add($container->get('parse_command'));
$application->run();
